<?php

/**
 * @file
 * Contains hooks to handle installation of this module.
 *
 * Specifically, a database table (blastdb) is created to store additional information
 * related to blast database nodes such as the name/path to the NCBI BLAST database files
 * and the type (protein or nucleotide) of the database.
 */


/**
 * Implements hook_install().
 */
function tripal_ontologyPages_install() {
   tripal_create_files_dir('tripal_ontologyPages');
   //$output = shell_exec('sh get_ontology_json.sh');
   //print($output);
}
